version: '3'

services:
  db:
    container_name: postgresql
    ports:
      - 5433:5432
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d