openapi: 3.0.0
info:
  title: Address Manager
  version: 1.0.0
servers:
  - url: localhost:8080
paths:
  /prefectures:
    get:
      summary: List all prefectures
      tags:
        - prefectures
      operationId: getPrefectures
      responses:
        '200':
          description: all prefectures
          content:
            application/json:
              schema:
                type: array
                $ref: "#/components/schemas/Prefecture"

components:
  schemas:
    Prefecture:
      title: 都道府県
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          description: 都道府県名
        nameKana:
          type: string
          description: 都道府県名のふりがな
      required:
        - id
        - name
        - nameKana