openapi: 3.0.0
info:
  title: Address Manager
  version: 1.0.0
servers:
  - url: localhost:8080
paths:
  /prefectures:
    $ref: "./paths/prefectures.yaml"
  /address:
    $ref: "./paths/address.yaml"
  /address/{id}:
    $ref: "./paths/address/{id}.yaml"

components:
  schemas:
    Prefecture:
      $ref: "./components/schemas/Prefecture"
    Gender:
      $ref: "./components/schemas/Gender"
